name: revheadz_vaz
description: "VAZ Simulator"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  soundpool: ^2.4.1

flutter:
  uses-material-design: true
